---
services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_PUBLIC_URL: "postgresql://postgres:postgres@db:5432/postgres"
      SECRET_KEY: "django-insecure-#!so9147lu!!&9t^dlomr26%m&2)(ybs)_3%ae5g@06gzhnz&@"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: ecommerce-site
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: otlp
      OTEL_LOGS_EXPORTER: otlp
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev # This ensures we can differentiate dev and live telemetry
      DJANGO_SETTINGS_MODULE: projectecommerce.settings # For our use case, especially
    ports:
      - 8181:8000
    depends_on:
      - db

  db:
    image: docker.io/postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ecommerce-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"



  collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC endpoint for receiving data
      - "4318:4318" # OTLP HTTP endpoint for receiving data
      - "8889:8889" # Prometheus metrics exporter endpoint
      - "55679:55679" # ZPages
    depends_on:
      - jaeger
      - prometheus

  # Jaeger is used for distributed tracing.
  jaeger:
    image: jaegertracing/all-in-one:1.55.0
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Jaeger trace receiver (for HTTP)
      - "14250:14250" # Jaeger trace receiver (for gRPC)

  # Prometheus is used for collecting and visualizing metrics.
  prometheus:
    image: prom/prometheus:v2.52.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"

  # Used to visualize data from multiple backends
  grafana:
    image: grafana/grafana:11.1.0 # Use a specific version for stability
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000" # Grafana UI
    environment:
      # Set default admin credentials
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - jaeger

volumes:
  ecommerce-db: {}
